### ISSUE TITLE
Diretrizes do projeto

### ISSUE THREAD

**Issue by woliveiras** [training-center/pastelcast#1]
Vamos usar essa issue para discutir todo o funcionamento do PastelCast!

Relacionado a [/sobre#5](https://github.com/training-center/sobre/issues/5)

**Comment by woliveiras** [comment]
@giovannicruz97 pode mover os pontos que foram levantados pra cá?

**Comment by alinebastos** [comment]
Eu só queria dizer que eu amei o nome!

**Comment by woliveiras** [comment]
Essa galera é criativa demais!

**Comment by JamileLima** [comment]
Opa! Gostei do nome uaheuha
Já quero participar :smile:

**Comment by khaosdoctor** [comment]
Dando continuidade àquela issue, eu gosto do seguinte funcionamento:

- Temos um host fixo (que provavelmente será o @giovannicruz97)
- Temos que definir a frequencia de postagem (eu acho que fica legal a cada 15 dias para não sobrecarregar, mas fica a critério do host, porque ele que vai ter que estar em todos os programas)
- A cada programa podemos (ou não) ter cohosts de apoio, como por exemplo no DNE quando temos o Eduardo e o Montanha, ou o Montanha e o Ramon. Esses coHosts podem ser um grupo fixo que vai rotacionando ou podemos incluir sempre gente nova
- Temos que criar uma pauta do que precisamos falar no programa e o Host será responsável por seguir a pauta com os convidados
- Estou pensando em ter no mínimo 0 e no máximo 3 convidados dependendo do programa, se não fica bagunçado

Coisas que temos que pensar para poder colocar ele no ar:

- Aonde vamos colocar no ar (itunes, SoundCloud, PodCast Addict etc etc)
- Quem vai editar
- Quem irá buscar as pautas e/ou como as pautas serão definidas (poderia ter uma votação grande aqui das pautas do programa e a galera votava)

O que acham? Perdi alguma coisa?

**Comment by giovannicruz97** [comment]
@wilcorrea acho que o @khaosdoctor disse tudo hahaah

**Comment by giovannicruz97** [comment]
Eu irei levantar essas informações e irei postar aqui na issue. Fiquem no aguardo, em breve essa documentação irá sair

**Comment by khaosdoctor** [comment]
Eu acho que era o @woliveiras não? kkk

**Comment by wilcorrea** [comment]
É comum já a confusão : )

**Comment by giovannicruz97** [comment]
É isso ai! Desculpe pela confusão

**Comment by raymonsanches** [comment]
Concordo com o que o @khaosdoctor falou ali em cima.

Ter hosts fixos é muito importante, pois dá identidade pro podcast e permite que o público se identifique com aquele ou aqueles que falam, de forma independente aos convidados.

Tenho só algumas observações sobre o hosting. Eu descartaria o SoundCloud como plataforma de hosting, ele anda meio digamos, inseguro. O outros que foram citados são na realidade agregadores e não hospedam nada.

O grande lance é ter um domínio fixo pra hospedar o feed. O feed é a audiência do podcast, precisa ser visto com cuidado pois se ficar mudando você acaba perdendo grande parcela de audiência.

Tem vários serviços excelentes de hospedagem, a maioria pagos, mas compensa muito utilizá-los. Acho que o mais importante também é tomar alguns cuidados na hora da gravação, captação do áudio e edição pra não dar aquele aspecto ruim pra quem tá ouvindo. 

Longe de mim ficar querendo cagar regra, mas posso ajudar em algumas coisas, já estamos fazendo o DNE há quase 3 anos e demos várias cabeçadas por aí.

=)

**Comment by giovannicruz97** [comment]
@raymonsanches Obrigado pelas dicas, certamente irá ajudar muito! Acho que a gente deveria ter um host fixo mesmo. Isso, realmente, cria uma identidade com o público. Sobre o feed: é importante termos um hosting mesmo, podemos começar a pensar em patrocinadores que possam nos ajudar, seja com renda ou com até mesmo um hosting pra gente. Além do mais, podemos criar um canal no Slack para discutir esse assunto e integrar com as issues que aparecem aqui. Que tal?

**Comment by woliveiras** [comment]
Interessante, @giovannicruz97 

Vou criar o canal PastelCast lá e podemos discutir as coisas. Só não esqueçam de criar as issues pra que outras pessoas possam ajudar se precisarem. :)

**Comment by giovannicruz97** [comment]
@jonathan-santos Nossa que demais! Pena que eu moro em Taubaté, SP. Porém, pra galera que mora ai e quer participar pode ser interessante. Vlw pela dica! 🤘

**Comment by alinebastos** [comment]
Ahhhhh, não vou poder participar snif!

**Comment by khaosdoctor** [comment]
Olha cara @jonathan-santos eu poderia ir participar, eu to aqui próximo deles haha

Concordo com tudo que o @raymonsanches disse! A experiência é a melhor educação haha

**Comment by giovannicruz97** [comment]
@alinebastos 💔 😭

**Comment by alinebastos** [comment]
Se tiver uma maneira de quem não mora por aí participar, tô dentro!

**Comment by woliveiras** [comment]
Eu posso participar como convidado dos primeiros gente, por que fazer direto não consigo. :cry: :cry:

**Comment by khaosdoctor** [comment]
@alinebastos Pode ser daí mesmo! Só combinar um dia e gravar de longe ai juntamos tudo haha

**Comment by woliveiras** [comment]
Galera, este projeto será tocado pelo @giovannicruz97 como sua iniciativa pessoal sem envolvimento do Training Center.

Qualquer coisa podem chamar ele pra agilizar o cast! \o/
